### ISSUE TITLE
When starting tms from outside tmux the created window is not responsive

### ISSUE THREAD

**Issue by brumik** [jrmoulton/tmux-sessionizer#92]
If you just open a terminal and do `tms` the created tmux session won't resize your tmux session after you resize the terminal. You need to run manually `resize` in terminal followed by `:resize-window -A` in tmux to get the resize and even then the tmux-line is bit screwed up. This is not a big issue as you can just bring up tmux and then use tms but wold be great for some scripting if this would work. 

Feel free to ask for more details.

- NixOS (linux)
- Alacritty 0.12.3
- tms 0.2.3

**Comment by petersimonsson** [comment]
I can't reproduce this, I'm admittedly using tms git on arch linux with alactrity 0.13.2 so one of those variables might be the reason. Hopefully a new alacritty and/or tms will fix it for you.

**Comment by junglerobba** [comment]
I was actually able to reproduce this (also NixOS, so even though I run unstable I was able to pull the versions from the 23.11 release in order to test this). Neither terminal nor tmux version matter, this only happens with the version of tmux-sessionizer that is packaged with that release, so some change since then seems to have already fixed it.
@brumik Since you're on NixOS, could you either use the flake provided by this github repo, or pull in tmux-sessionizer from the unstable channel? That would very likely fix your issue.

**Comment by brumik** [comment]
I was pulling the package from unstable, though since then it may have been updated there? In any case I was just put depth 1 for all my git root folders and it works great for me. Though it is good to know that it is fixed upstream. Thank you!

Since this seems an "old version" problem, I'll close the issue.
