### ISSUE TITLE
Ability to add paths to config that are not .git projects

### ISSUE THREAD

**Issue by caliguIa** [jrmoulton/tmux-sessionizer#93]
Hi this maybe out of scope for the project but I love the tool.

For work we use a monorepo, I mainly work in one area of said monorepo.

Obviously the .git file exists at the top level root of the project. However I work only in a directory within the project. 

I would love to be able to set "root_dir/targer_dir" target dir as a path in my tms config if possible.

Thanks

**Comment by jrmoulton** [comment]
I think this is definitely in scope. 

I'm low on time right now but I think this should be fairly easy to implement. Right now we check if a folder is a git folder by trying to open it with git2. Instead we could first check for a file that indicates that it is a root directory. 

In the config we could take a list of file types that could be checked for.

**Comment by appleseedexm** [comment]
I would also offer my time, but my rust's very basic too :D 

For starters I would have just added a list of folders to manually add - my usecase doesnt have a specific root-file I would want to add and it might be much easier to implement. 

Root-files are a tricky business since they're rarely exclusive (i.e. the current implementation has bugs with git worktrees).
